### ISSUE TITLE
Doesn't work with Dockerfile

### ISSUE THREAD

**Issue by alarv** [sheshbabu/fastapi-structured-json-logging-demo#1]
Using the suggested Dockerfile from fastapi:
```Dockerfile
FROM python:3.10

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
COPY ./src /code/src

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./main.py /code/

EXPOSE 8002

CMD ["fastapi", "run", "main.py", "--port", "8002"]
``` 

this logging configuration does not work, do you have any suggestions on how to make it work inside a docker image inside a kubernetes cluster?

**Comment by sheshbabu** [comment]
Hello,

I use `python -m src.main` as the docker entrypoint and it works well in k8s. Can you give it a try?

Cheers,
Shesh
